spring:
 datasource:
#   数据源基本配置
   username: root
   password: pps123
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://120.79.204.37:3306/springSecurityTest?characterEncoding=utf-8
   type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
   initialSize: 5
   minIdle: 5
   maxActive: 20
   maxWait: 60000
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: SELECT 1 FROM DUAL
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
   poolPreparedStatements: true
 jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

 server:
    port: 8080
    servlet:
      context-path: /
 thymeleaf:
    prefix: classpath:/templates/